apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: user-<username>
spec:
  groups:
  - system:authenticated
  request: <REDACTED> # base64 encoded csr
  usages:
  - digital signature
  - key encipherment
  - client auth
